ego_scan_topic: "/scan"
ego_odom_topic: "/odom"
opp_odom_topic: "/opp_odom"
ego_drive_topic: "/drive"
lap_count_topic: "/lap_count"
lap_time_topic: "/lap_time"
collision_topic: "/collision"
race_info_topic: "/race_info"
gym_reset_topic: "/reset_gym_env"

# fixed vals DO NOT CHANGE
scan_fov: 4.7
scan_beams: 1080
scan_distance_to_base_link: 0.275

map_path: "/f1tenth_gym/maps/map.yaml"
map_img_ext: ".png"
executable_dir: "/f1tenth_gym/build/"

waypoints_path: "/catkin_ws/src/f1tenth_gym_ros/maps/opp_ref_path.csv" # do use the name "opp_ref_path.csv"
# waypoints_path: "/home/honda/sim_ws/src/f1tenth_gym_ros/maps/opp_ref_path.csv" # do use the name "opp_ref_path.csv"

# gym initial states
ego_initial_x: 0.0
ego_initial_y: 0.0
ego_initial_theta: 0.0

opp_initial_x: -2.0
opp_initial_y: -1.0
opp_initial_theta: 0.0

seed: 42
